name: ci_demo

on:
  push:
    branchs: [master]
  pull_request:
    branchs: [master]

# create a job
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 建環境
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"

      # 運行測試
      - name: Run Tests
        run: | 
          pytest tests/test_area.py -v -s
      
